### PR TITLE
fromFormat handles non breakable spaces. Fixes #714

### LINKED ISSUE #714: Library fails to parse time using fromFormat
```
Settings.defaultLocale = 'es-ES';

DateTime.fromFormat('11:22 am', 'hh:mm a');
```
returns `"the input "11:22 am" can't be parsed as format hh:mm a"`
in case of `es-ES` locale `/^(\d{2})(:)(\d{2})(\ )(a\.? m.|p\.? m.)$/i` was used and for `en-US` - `/^(\d{2})(:)(\d{2})(\ )(AM|PM)$/i`

expected result: `DateTime.fromFormat('11:22 am', 'hh:mm a')` to be parsed without exceptions

### PR DESCRIPTION
**Pull request by GillesDebunne**
The problem was the the `es-ES` meridiem strings are _"a. m."_ and _"p. m."_, but with a **non breakable space** in the middle (char code 160). Since the input string used a regular space, it was not matched correctly.

This PR changes the RegExp to consider spaces and non breakable spaces characters interchangeably.

It also adds a `global` flag to the dots, so that they are *all* considered optional.

### CODE REVIEW

File: src/impl/tokenParser.js [hunk 1]
```diff
@@ -13,12 +13,20 @@ function intUnit(regex, post = i => i) {
 }
 
 function fixListRegex(s) {
+  const nbsp = String.fromCharCode(160);
+  const spaceOrNBSP = `( |${nbsp})`;
   // make dots optional and also make them literal
-  return s.replace(/\./, "\\.?");
+  // make space and non breakable space characters interchangeable
+  return s.replace(/\./g, "\\.?").replace(new RegExp(spaceOrNBSP, "g"), spaceOrNBSP);
```
Comment (icambron) [inline src/impl/tokenParser.js:20]: can commonize `new RegExp(spaceOrNBSP, "g")`

**Comment by icambron** [comment]
looks good, left one comment

**Comment by icambron** [comment]
@GillesDebunne Went through all the tickets. Great work. Merge whenever you'd like; when you're done, I'll cut a release.

File: test/datetime/tokenParse.test.js [hunk 2]
```diff
@@ -66,6 +68,41 @@ test("DateTime.fromFormat() throws if you specify meridiem with 24-hour time", (
...
+// #714
+test("DateTime.fromFormat() makes dots optional and handles non breakable spaces", () => {
+  function parseMeridiem(input, isAM) {
+    const d = DateTime.fromFormat(input, "hh:mm a");
+    expect(d.hour).toBe(isAM ? 10 : 22);
+    expect(d.minute).toBe(45);
+    expect(d.second).toBe(0);
+  }
+
+  // Meridiem for this locale is "a. m." or "p. m.", with a non breakable space
```
Comment (jayaddison) [inline test/datetime/tokenParse.test.js:80]: Is this a typical representation of meridiems in the `es-ES` locale? (or is this a test case to handle some larger set of nbsp situations?)
