### PR TITLE
Use Symbol for Node's custom inspect

### LINKED ISSUE #276: DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated on Node v10+
```
//index.mjs
import luxon from 'luxon'; // import { DateTime } from 'luxon' not working yet (https://github.com/moment/luxon/issues/252)
const DateTime = luxon.DateTime;
console.log(DateTime.local())
```

=>

```
$ node -v
v10.4.1
$ node --trace-deprecation --harmony --experimental-modules index.mjs
DateTime {
  ts: 2018-06-17T11:28:08.858+02:00,
  zone: Europe/Rome,
  locale: en-US }
(node:99259) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
    at formatValue (util.js:467:31)
    at inspect (util.js:328:10)
    at Proxy.formatWithOptions (util.js:182:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at Object.log (/Users/damz/Desktop/yarsk/node_modules/better-console/index.js:22:17)
    at file:///Users/damz/Desktop/yarsk/index.mjs:30:9
    at ModuleJob.run (internal/modules/esm/module_job.js:106:14)
```

### PR DESCRIPTION
**Pull request by shvaikalesh**
Resolves #276.

Node's `inspect` is fairly useful, let's try to keep it. I don't exceptionally like the solution at hand, but I have an idea how we can make it better if Node.js would support it.

### CODE REVIEW

File: src/impl/util.js [hunk 1]
```diff
@@ -203,3 +203,11 @@ export function normalizeObject(obj, normalizer, ignoreUnknown = false) {
 export function timeObject(obj) {
   return pick(obj, ['hour', 'minute', 'second', 'millisecond']);
 }
+
+export const customInspectSymbol = (() => {
+  try {
+    return require('util').inspect.custom; // eslint-disable-line global-require
+  } catch (_err) {
+    return Symbol('util.inspect.custom');
```
Comment (icambron) [inline src/impl/util.js]: Can you explain this? I'm a little out of the loop on this stuff

Comment (shvaikalesh) [reply src/impl/util.js]: Oh, sure.

The recommended way for custom routine during `inspect` is to specify a symbol, which is exposed as `util.inspect.custom`.

However, for browser environments, where `require` is unavailable, we need a clean no-op. That is handled in `catch` clause: `util.inspect.custom` is just for show, it is merely a description, could be anything. We simply return a new symbol (that won't be used by anyone) so we can simply do

```js
import { customInspectSymbol } from 'utils';

[customInspectSymbol]() {
  // ...
}
```

in our classes, without any helpers or extra checks.

Comment (icambron) [reply src/impl/util.js]: Got it

**Comment by icambron** [comment]
thanks!
